language: java
# install: ant deps

before_install:
  - java -version

script:
  - jdk_switcher use oraclejdk8
  - ./download_processing.sh
  - ./build_Serial_Processing.sh

after_failure:
  - find . | egrep "processing-java"

after_success:
  - find . | egrep "processing-java"
